---
- hosts: all
  remote_user: root
  vars:
    SAS_USER: sas
    SAS_GROUP: sas
    CAS_PORT: 17893
    CAS_GC_PORT: 27893
    CAS_HTTP_PORT: 37893
    tar_file: /vagrant/cas-laxno-1.0.0-20160118.104700-1.tar.gz

  tasks:
  - name: create /opt dir
    file: path=/opt state=directory

  - name: unpack CAS tarball
    unarchive: src={{ tar_file }} dest=/opt

  - name: copy config files
    copy: src=/vagrant/*.hosts dest=/opt/cas
    copy: src=/vagrant/cas.settings.local dest=/opt/cas

  - name: modify the launchconfig to support host authentication
    lineinfile: dest=/opt/cas/bin/launchconfig line='launchServerAs={{ SAS_USER }}'
    lineinfile: dest=/opt/cas/bin/launchconfig line=useHostToken
    lineinfile: dest=/opt/cas/bin/launchconfig line=externalIdent

  - name: add PAM configuration
    copy: src=/vagrant/cas.pam dest=/etc/pam.d/cas owner=root

  - name: add sas group
    group: name=sas state=present

  - name: add sas user
    user: name={{ SAS_USER }} shell=/bin/bash group=sas home=/home/sas createhome=yes generate_ssh_key=yes

  - name: copy ssh keys
    copy: src=/vagrant/id_rsa dest=/home/sas/.ssh/id_rsa owner=sas group=sas mode=0600
    copy: src=/vagrant/id_rsa.pub dest=/home/sas/.ssh/id_rsa.pub owner=sas group=sas mode=0600

  - name: create authorized_keys dir
    file: path=/home/sas/.ssh/authorized_keys state=directory owner=sas group=sas mode=0700

  - name: copy ssh key to authorized_keys dir
    copy: src=/home/sas/.ssh/id_rsa.pub dest=/home/sas/.ssh/authorized_keys/id_rsa.pub owner=sas group=sas mode=0600

  - name: add SAS_USER to souders file
    lineinfile: dest=/etc/sudoers line="{{ SAS_USER }} ALL=(ALL) NOPASSWD:ALL"

  - name: change owner on CAS dir
    file: path=/opt/cas owner={{ SAS_USER }} group={{ SAS_GROUP}} recurse=yes

  - name: set permsions on caslaunch
    file: path=/opt/cas/bin/caslaunch owner=root mode=4755
